steps:
- id: 'deploy-sample-wf'
  name: 'gcr.io/cloud-builders/gcloud'
  args: 
    - workflows
    - deploy
    - sample-wf1
    - --source
    - ./wf1/sample_wf.yaml
    - --service-account
    - "sa-workflows@${_PROJECT}.iam.gserviceaccount.com"
    - --location
    - asia-northeast1

- id: 'deploy-sample-wf2'
  name: 'gcr.io/cloud-builders/gcloud'
  args: 
    - workflows
    - deploy
    - sample-wf2
    - --source
    - ./wf2/sample_wf2.yaml
    - --service-account
    - "sa-workflows@${_PROJECT}.iam.gserviceaccount.com"
    - --location
    - asia-northeast1
    - --env-vars-file
    - ./env/dev.yaml

substitutions:
  _PROJECT: ''

# gcloud scheduler jobs create http JOB_NAME \
#     --schedule="FREQUENCY" \
#     --uri="https://workflowexecutions.googleapis.com/v1/projects/PROJECT_ID/locations/REGION_NAME/workflows/WORKFLOW_NAME/executions" \
#     --message-body="{\"argument\": \"DOUBLE_ESCAPED_JSON_STRING\"}" \
#     --time-zone="TIME_ZONE" \
#     --oauth-service-account-email="SERVICE_ACCOUNT_NAME@PROJECT_ID.iam.gserviceaccount.com"

## https://docs.cloud.google.com/workflows/docs/schedule-workflow?hl=ja
